stages:
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "20"
  PNPM_CACHE_FOLDER: ".pnpm-store"

image: node:${NODE_VERSION}

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store
    - node_modules/

before_script:
  - corepack enable
  - corepack prepare pnpm@9 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install

build:
  stage: build
  script:
    - pnpm nuxi build
  artifacts:
    paths:
      - .output/server/index.mjs
    expire_in: 7 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "lab4"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint:
  stage: test
  script:
    - pnpm exec eslint "**/*.{vue,ts,js}"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

tests:
  stage: test
  script:
    - pnpm vitest run
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy:
  stage: deploy
  script:
    - echo "Deploying to $TARGET_ENV"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'